### ISSUE TITLE
Running using Docker fails

### ISSUE THREAD

**Issue by ds33s** [IanVermes/vep_api#1]
Trying to run the app using Docker, I'm getting failed tests:
`docker-compose up --build`

![Screenshot 2020-03-30 at 11 48 19](https://user-images.githubusercontent.com/50616783/77904655-d3043180-727c-11ea-8687-34a75c3eea2a.png)

Can you please advise how to proceed?

**Comment by IanVermes** [comment]
Sure. I’ll take look this afternoon on a virgin environment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IanVermes** [comment]
Apologies for the delay Doron.  The two tests that fail are executed at run time and not at build time. Both are dependent on systems calls to the perl `vep` program then touch the exposed volume at the machine-to-docker interface. They both failed on my vanilla laptop setup as well! 

However the tests were rescued when I initialised the `vep_data` directory with the human 99_GRCh38 genomic data. 

```
/Users/vanilla
├── Desktop
├── Documents
│   └── git-clones
│       └── vep_api
├── Downloads
├── Library
├── Movies
├── Music
├── Pictures
├── Public
└── vep_data
    └── homo_sapiens
        └── 99_GRCh38
```

To do this, either:
1. While vep_api is you current directory do ```$ docker-compose run web perl INSTALL.pl -a cf -s homo_sapiens -y GRCh38```, download 16 GB of genomic data and let INSTALL.pl create the directory.
2. If the genomic data exists elsewhere, move it to your user directory and mimic the `vep_data` directory.
3. Change the `docker-compose.yml` volume paths to point to a different `vep_data`. Currently its set as `$HOME/vep_data:/opt/vep/.vep`

**Comment by IanVermes** [comment]
I mentioned the volume setup in the README and it's borrowed from [the official instructions](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker), but I should have made it clearer. My apologies.

Please let me know how you get on.

**Comment by ds33s** [comment]
Thanks Ian. That looks fine.
